[dedication]
== Dedicatória

[verse]
Dedico este livro a
   Raquel,
     Sandra,
       Mauro,
         Airton e
           Sérgio,

os cinco maravilhosos filhos que Deus deu de presente a mim e a Nira.
Vocês são o maior tesouro e a maior causa de júbilo e alegria que
recebemos sobre esta terra! Bem, sinto muita falta e saudades de
Mauro, mas sei que qualquer dia desses vamos nos encontrar de novo, no
céu, e, enquanto isso, eu e Nira queremos aproveitar mais e melhor
nossos dias com nossos outros filhos, e netos.


Agradeço à minha esposa, Valdenira Nunes de Menezes Silva, por ter
assumido muitas das minhas tarefas, a fim de me dar tempo para
escrever este livro em curto prazo de tempo. 

Agradeço aos professores Rivanildo Garcia da Silva e José Miguel
Aroztegui por suas contribuições e revisões do cap. 1; Joseluce de
Farias Cunha, cap. 2; Lucídio dos Anjos Formiga Cabral, cap. 6. 

Agradeço ao alunos Túlio Albuquerque Pascoal, cap. 3. Os exemplos das
falácias citadas no cap. 2 são adaptações de respostas por meus alunos
de Linguagens Formais, em trabalho para casa, no período 2012.2.


[verse]
3 Quando vejo os teus céus, obra dos teus dedos, a lua e as estrelas que preparaste;
4 Que é o homem mortal para que te lembres dele? e o filho do homem, para que o visites?
5 Contudo, pouco menor o fizeste do que os anjos, e de glória e de honra o coroaste.
6 Fazes com que ele tenha domínio sobre as obras das tuas mãos; tudo puseste debaixo de seus pés:
7 Todas as ovelhas e bois, assim como os animais do campo.
8 As aves dos céus, e os peixes do mar, e tudo o que passa pelas veredas dos mares.
9 Ó SENHOR, Senhor nosso, quão admirável é o teu nome sobre toda a terra!
Salmo 8:3-9 (LTT)

