Parabéns, meu aluno e amigo, pela sua decisão de estudar e fazer um
curso superior, particularmente Licenciatura em Computação na UFPB,
enquanto muitos se abandonam ao não fazer nada da vida. Parabéns. Sei
que alguns de vocês trabalham, muitos moram onde não há muitos meios e
oportunidades, por isso lhe dou pessoalmente parabéns pela garra e
determinação em fazer este curso através do EAD. 

Tenho a firme convicção que, com sua disciplina e determinação amigo
(isto será a chave!), a EAD pode formar profissionais de grande
competência, EAD pode ser o futuro da educação, inclusive revertendo
paradigmas seculares,
http://usatoday30.usatoday.com/life/people/story/2012-05-30/sal-khan-profile-khan-academy/55270348/1.
Sou um entusiasta da EAD, mas deixe-me avisá-lo, ela precisa de duas
coisas básicas: autodisciplina e esforço. Se você não tiver essas
qualidades e de modo nenhum as quiser desenvolver, deixe-me ser
franco, dificilmente conseguirá muito na vida, em quase nada. Na EAD,
você precisa ter a autodisciplina de diariamente dedicar várias horas
ao estudo. Sozinho ou em grupo, você precisa fazer por si mesmo todos
os exemplos e pelo menos 1/3 dos exercícios, saltando de três em três.
Vou bater nessa mesma tecla em todas as unidades.

Quanto ao curso, minha aspiração é que ele lhe faça ainda mais um
vencedor, em DUAS vertentes: a) tendo capacidade técnica para, se
imposto pela vida, disputar corrida com os bacharéis em Ciência da
Computação e cursos similares (por que não?); e b) sendo o
profissional por excelência na nobre profissão de professor na
educação básica e na técnico- profissionalizante, talvez fazendo
pós-graduação e ensinando em universidades. Almejo e antevejo duas
vertentes à sua disposição, para seu futuro.

Quanto à disciplina em si (Matemática Elementar) de que tomo como
privilégio poder escrever este livro e lhe ensinar, é uma das
primeiras e mais básicas para tudo o mais. Não é uma disciplina fácil,
pois é muito densa, tem muito conteúdo em pouco tempo e espaço, mas
tem que ser assim. Se, ao final dela, você não dominar seu assunto
muito bem, provavelmente terá muita dificuldade para acompanhar as 3
outras disciplinas de Matemática, mais as 3 disciplinas Estrutura de
Dados (que avançará em grafos), Teoria da Computação (que avançará em
lógica e outros formalismos) e Agentes Inteligentes (idem).

O objetivo específico da disciplina é lhe capacitar plenamente nos
assuntos da sua ementa: 1) Teoria dos Conjuntos: axiomas, operações
elementares, relações, funções, ordenação, números naturais, conjuntos
contáveis e incontáveis. 2) Introdução à Lógica Matemática. 3)
Recorrência e Indução. 4) Noções básicas: proposições,
provas/demonstrações. 5) Métodos de Enumeração: permutação, combinação
e o teorema de Ramsey. 6) Grafos: terminologia básica, classes de
grafos, grafos ponderados e orientados, ciclos e circuitos, árvores.
Adicionei como um 7º tópico Teoria dos Números, ao invés de abordá-lo
distribuído nos tópicos anteriores. Fica melhor assim.

Os livros-texto da disciplina, se você tiver acesso a eles em papel ou
computador, são:

- GERSTRING, J. L. Fundamentos Matemáticos para Ciência da Computação.
  Rio de Janeiro: LTC, 3 ed., 1995.
- ROSEN, K. H. Discrete Mathematics and its Applications. 4. ed.
  McGraw-Hill, 1999.
- IEZZI, G. et al. Fundamentos de Matemática Elementar: conjuntos e
  funções. 6 ed. São Paulo: Atual, Vol. 1, 1993..
- DAGHLIAN, J. Lógica e Álgebra de Boole. São Paulo: Editora Ática,
  1990.  
  
NOTE: Creio que este presente livro deverá ser suficiente para a maior
parte da disciplina, você só precisando consultar os livros-texto se
se interessar por maior aprofundamento em certos tópicos que despertem
seu interesse. Também, espalhados por este livro, colocarei links para
vários outros livros, notas de aula e artigos disponibilizados na
internet, particularmente quando eu tiver extraído exemplos e
problemas deles, ou quando eu quiser sugerir que você faça tais
exercícios.

O fórum de alunos, os tutores, e eu (o professor) queremos e vamos
ajudá-lo (nessa ordem). Mas, repito, o início de tudo, a chave, é você
mesmo ser determinado e disciplinado, cada semana dedicando 4 a 8
horas para estudar este livro com todo afinco.

Sucesso, meu amigo. Comecemos nossa jornada na Matemática Elementar.
Que, ao final do seu esforço, mesmo duro, você a avalie como lhe tendo
dado a satisfação de ter dominado o assunto, e eu a satisfação de lhe
ter ajudado nisso.

[[como_estudar]]
=== Como estudar 

Vamos lhe passar a ideia de como estudar para profundamente aprender e
reter cada capítulo de qualquer livro sobre qualquer assunto.

Cada estudo, se for para você dominar o assunto e ser bem aprovado e
reter o que aprendeu, deve ser feito em três varreduras:

- 1ª varredura, de CONTATO (mais ou menos de 20 minutos para 10
  páginas de Matemática?): leia todo o capítulo ou seção sem atropelo
  mas sem parar em nada: mesmo se você ler 2 vezes um parágrafo e
  ainda não o entender perfeitamente, siga em frente num fluxo
  contínuo, seu objetivo sendo apenas o de ter uma ideia global da
  estrutura e conteúdo de tudo, saber o que é mais importante e o que
  é apenas caminho para lá, sem você, prematuramente, se deter em
  detalhes finos.

- 2ª varredura, de DOMÍNIO (mais ou menos de 4 horas para 10 páginas
  de Matemática?): releia toda a parte do livro, agora com toda a
  atenção e cuidado e intensidade, procurando perfeitamente entender
  cada definição (até o ponto de poder reexpressá-la [oralmente] em
  suas próprias palavras); e perfeitamente entender cada prova ou
  demonstração (idem); e perfeitamente entender cada exemplo (idem). 
+
--

Em paralelo, sublinhe a grafite, bem leve, os 10% que achar mais
importantes. 

Depois de ler e compreender cada exemplo, feche o livro e tente
fazê-lo escrevendo-o com suas próprias palavras, depois compare com o
livro. 

Finalmente, faça 1 a cada 3 ou 5 dos problemas propostos.

A chave para o real aprendizado é você fazer muitas dezenas de
problemas (eu fiz muitas centenas ou alguns milhares, para o
vestibular, para Cálculo I e II, etc.). Começando pelos exemplos e
problemas mais fáceis dos livros mais fáceis, e prosseguindo
paulatinamente para os mais difíceis. Sem resolver problemas assim,
somente lendo a teoria, você nunca chegará nem perto de dominar nenhum
assunto, provavelmente poderá ser reprovado 2 ou 3 vezes em cada
disciplina mais pesada.

--
 
- 3ª varredura, de SÍNTESE E MEMORIZAÇÃO (mais ou menos de 20 minutos
  para 10 páginas de Matemática?): Escolha os 2% mais importantes e
  mude-lhes o sublinhado para ser em caneta vermelha ou marcador
  amarelo: as fórmulas, os teoremas, o que você sabe que precisará
  guardar em sua memória para sempre. Há quem goste de sumariar tudo
  numa espécie de ``cola'' de ½ página (ou miniatura de 10cm), somente
  para fixar o que mais precisa saber (nunca para fins desonestos,
  claro).


Prof. Hélio de Menezes Silva,      mar.2014.1.
DCC/ CI/ UFPB – Universidade Federal da Paraíba, Campus de João Pessoa.

////
Sempre terminar o arquivo com uma nova linha.
////
